### ISSUE TITLE
Notification by Windows Notification or Sound?

### ISSUE THREAD

**Issue by alfanzain** [OctopusRage/dota-strat-assistant#1]
Better with sound like '1 minutes remaining Bounty Rune will be spawned' or 'About 1 minutes remaining Roshan will be respawned'.

**Comment by OctopusRage** [comment]
for current roadmap only text notification will appear, i know it would be better to use the notification but now my priority is working on timer core logic. 
i think sound notification can be done like you input your own sound, then record it and save the notification rather than app read the notification text

**Comment by OctopusRage** [comment]
gladly accept your PR if you have an idea how to put it in (y)
